"""Tests for core.parser: JSONL transcript parsing."""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

import pytest

from agent_sessions.core.parser import (
    decode_project_dir,
    extract_text,
    is_real_user_prompt,
    parse_session,
    parse_ts,
)


def _write_jsonl(path: Path, lines: list[dict]) -> None:
    path.write_text("\n".join(json.dumps(line) for line in lines) + "\n")


# ----------------------- decode_project_dir ------------------------


def test_decode_project_dir_absolute_form():
    assert (
        decode_project_dir("-Users-nathan-Developer-proj-foo")
        == "/Users/nathan/Developer/proj/foo"
    )


def test_decode_project_dir_without_leading_dash():
    assert decode_project_dir("Users-nathan-x") == "Users/nathan/x"


# --------------------------- parse_ts ------------------------------


def test_parse_ts_handles_z_suffix():
    assert parse_ts("2026-05-18T10:00:00Z") == dt.datetime(
        2026, 5, 18, 10, 0, tzinfo=dt.UTC
    )


@pytest.mark.parametrize("bad", [None, "", "not-a-date", "2026-99-99"])
def test_parse_ts_returns_none_for_bad_input(bad):
    assert parse_ts(bad) is None


# -------------------------- extract_text ---------------------------


def test_extract_text_passes_strings_through():
    assert extract_text("hello") == "hello"


def test_extract_text_concatenates_text_blocks_and_skips_non_text():
    blocks = [
        {"type": "text", "text": "one"},
        {"type": "tool_use", "name": "X"},
        {"type": "text", "text": "two"},
    ]
    assert extract_text(blocks) == "one\ntwo"


def test_extract_text_returns_empty_for_unknown_shapes():
    assert extract_text(None) == ""
    assert extract_text({"type": "text", "text": "ignored"}) == ""


# ----------------------- is_real_user_prompt -----------------------


@pytest.mark.parametrize(
    "bad",
    [
        "",
        "   ",
        "<command-name>foo",
        "<command-stdout>bar",
        "<local-command-out>baz",
        "<system-reminder>hello",
        "Messages below were generated by Claude",
    ],
)
def test_is_real_user_prompt_filters_system_text(bad):
    assert not is_real_user_prompt(bad)


def test_is_real_user_prompt_accepts_normal_text():
    assert is_real_user_prompt("how do i do the thing")


# --------------------------- parse_session -------------------------


@pytest.fixture
def session_jsonl(tmp_path: Path) -> Path:
    """A transcript that exercises every branch of parse_session."""
    proj = tmp_path / "-Users-nathan-Developer-proj-foo"
    proj.mkdir()
    path = proj / "abc-123.jsonl"
    _write_jsonl(
        path,
        [
            # cwd override + first real prompt
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:00Z",
                "cwd": "/explicit/cwd",
                "message": {"content": "real first prompt"},
            },
            # title
            {"type": "ai-title", "aiTitle": "Refactor the thing"},
            # filtered: command-name wrapper
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:05Z",
                "message": {"content": "<command-name>foo"},
            },
            # filtered: sidechain user (entire branch skipped)
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:06Z",
                "isSidechain": True,
                "message": {"content": "do not count"},
            },
            # filtered: meta user
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:07Z",
                "isMeta": True,
                "message": {"content": "also nope"},
            },
            # second real prompt
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:10Z",
                "message": {"content": "second real prompt"},
            },
            # assistant turn with usage + TaskCreate
            {
                "type": "assistant",
                "timestamp": "2026-05-18T10:00:15Z",
                "message": {
                    "content": [
                        {"type": "text", "text": "ok here goes"},
                        {
                            "type": "tool_use",
                            "name": "TaskCreate",
                            "input": {
                                "taskId": "t1",
                                "subject": "Do thing",
                                "description": "details",
                            },
                        },
                    ],
                    "usage": {
                        "input_tokens": 100,
                        "output_tokens": 50,
                        "cache_creation_input_tokens": 20,
                        "cache_read_input_tokens": 200,
                    },
                },
            },
            # TaskUpdate flips t1 to completed
            {
                "type": "assistant",
                "timestamp": "2026-05-18T10:00:20Z",
                "message": {
                    "content": [
                        {
                            "type": "tool_use",
                            "name": "TaskUpdate",
                            "input": {"taskId": "t1", "status": "completed"},
                        },
                    ],
                    "usage": {"input_tokens": 10, "output_tokens": 5},
                },
            },
            # sidechain assistant: usage must NOT be totaled
            {
                "type": "assistant",
                "timestamp": "2026-05-18T10:00:25Z",
                "isSidechain": True,
                "message": {
                    "content": [{"type": "text", "text": "x"}],
                    "usage": {"input_tokens": 99999, "output_tokens": 99999},
                },
            },
        ],
    )
    # Non-JSON garbage line must be skipped without crashing
    with path.open("a") as f:
        f.write("not-json\n")
    return path


def test_parse_session_full_transcript(session_jsonl: Path):
    sess = parse_session(session_jsonl)
    assert sess is not None
    assert sess.session_id == "abc-123"
    assert sess.cwd == "/explicit/cwd"
    assert sess.title == "Refactor the thing"
    assert sess.first_prompt == "real first prompt"
    assert sess.last_prompt == "second real prompt"
    assert sess.user_msg_count == 2
    assert sess.input_tokens == 110
    assert sess.output_tokens == 55
    assert sess.cache_create_tokens == 20
    assert sess.cache_read_tokens == 200
    assert sess.billable_tokens == 185
    assert sess.total_tokens == 385
    assert "t1" in sess.tasks
    assert sess.tasks["t1"].subject == "Do thing"
    assert sess.tasks["t1"].status == "completed"
    assert sess.incomplete_tasks == []
    assert len(sess.completed_tasks) == 1


def test_parse_session_falls_back_to_decoded_project_dir(tmp_path: Path):
    proj = tmp_path / "-Users-nathan-Developer-proj-foo"
    proj.mkdir()
    path = proj / "s.jsonl"
    _write_jsonl(
        path,
        [
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:00Z",
                "message": {"content": "hi"},
            }
        ],
    )
    sess = parse_session(path)
    assert sess is not None
    assert sess.cwd == "/Users/nathan/Developer/proj/foo"


def test_parse_session_returns_none_without_timestamps(tmp_path: Path):
    proj = tmp_path / "-x"
    proj.mkdir()
    path = proj / "no-ts.jsonl"
    _write_jsonl(path, [{"type": "user", "message": {"content": "hi"}}])
    assert parse_session(path) is None


def test_parse_session_returns_none_for_empty_file(tmp_path: Path):
    proj = tmp_path / "-y"
    proj.mkdir()
    path = proj / "empty.jsonl"
    path.write_text("")
    assert parse_session(path) is None


def test_parse_session_returns_none_when_file_missing(tmp_path: Path):
    assert parse_session(tmp_path / "ghost.jsonl") is None


def test_parse_session_taskcreate_without_explicit_id_gets_index(tmp_path: Path):
    proj = tmp_path / "-z"
    proj.mkdir()
    path = proj / "x.jsonl"
    _write_jsonl(
        path,
        [
            {
                "type": "user",
                "timestamp": "2026-05-18T10:00:00Z",
                "message": {"content": "go"},
            },
            {
                "type": "assistant",
                "timestamp": "2026-05-18T10:00:01Z",
                "message": {
                    "content": [
                        {
                            "type": "tool_use",
                            "name": "TaskCreate",
                            "input": {"subject": "anon task"},
                        }
                    ],
                    "usage": {},
                },
            },
        ],
    )
    sess = parse_session(path)
    assert sess is not None
    assert len(sess.tasks) == 1
    only_task = next(iter(sess.tasks.values()))
    assert only_task.subject == "anon task"
    assert only_task.status == "pending"


def test_parse_session_start_and_end_span_messages(session_jsonl: Path):
    sess = parse_session(session_jsonl)
    assert sess is not None
    assert sess.start_ts == dt.datetime(
        2026, 5, 18, 10, 0, 0, tzinfo=dt.UTC
    )
    assert sess.end_ts == dt.datetime(
        2026, 5, 18, 10, 0, 25, tzinfo=dt.UTC
    )
